game/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('redvblue.urls')),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

redvblue/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate
import re
from redvblue.models import Team


class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, required=True)
    password = forms.CharField(label='Password', max_length=100, required=True, widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        user = authenticate(
            username=cleaned_data.get('username'),
            password = cleaned_data.get('password'))
        if user is None:
            self._errors['username'] = self.error_class(['You sure?'])
            self._errors['password'] = self.error_class(['Wrong wrong wrong'])
            raise ValidationError('User doesn\'t exist. Or details entered incorrectly')
        return self.cleaned_data


class UserForm(forms.Form):
    display_name = forms.CharField(label='Display Name', max_length=100, required=True)
    username = forms.CharField(label='Username', max_length=100, required=True)
    password = forms.CharField(widget=forms.PasswordInput, label='Password', max_length=100, required=True)
    avatar = forms.FileField(label='Avatar', required=True)

    def clean(self):
        display_name_regex = r'[A-Za-z -]'
        user_regex = r'[A-Za-z0-9@#.]'
        cleaned_data = super().clean()
        display_name = cleaned_data.get('display_name')
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        if len(password) <= 8:
            self._errors['password'] = self.error_class([' Must be longer than 8 characters'])
        if not re.match(display_name_regex, display_name):
            self._errors['display_name'] = self.error_class(['Wrong format, see below'])
        if not re.match(user_regex, username):
            self._errors['username'] = self.error_class(['Wrong format, see below'])
        return self.cleaned_data


class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = (
                'name',
                'color',
                'admin',
                'avatar_img',)
    def clean(self):
        cleaned_data = super().clean()
        team_name = cleaned_data.get('team_name')
        team_color = cleaned_data.get('team_color')
        kregex = r'[A-Za-z0-9]'
        if not team_color:
            self.errors['team_color'] = self.error_class(['Don\'t forget team color'])
        if not re.match(kregex, team_name):
            self.errors['team_name'] = self.error_class(['Name must be Alphanumeric'])
        return self.cleaned_data

templates/base.html
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% if request.user.is_authenticated %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/">Home</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'profile_update' %}"">Edit Profile</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'log_out' %}">Logout</a>
            </li>
        </ul>
      </div>
    </nav>
{% endif %}

templates/home.html
{% load bootstrap5%}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block content %}
{% include 'base.html'%}
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>Home</title>
    <style>
        #id_username {width: 300px; height: 40px}
        #id_password {width: 300px; height: 40px}
        #id_display_name {width: 300px; height: 40px}
    </style>
</head>
{% if user.is_authenticated %}
    <body style="background-image: url('{{user.player.avatar_img.url}}'); background-repeat: repeat" >
        <div style="  margin: auto; width: 50%; padding: 10px; ">
            <div class="col-lg-12">
                <div class="panel panel-success">
                    <div class="panel-body">
                        <h1 style="color:{{message.text_color}} "> {{message.team_message}}</h1>
                        <ul class="nav nav-tabs">
                            {% if user.player.team %}
                                <div class="col-lg-4">
                                    <a  href="{% url 'team' pk=user.player.team.id %}" class="btn btn-primary btn-lg"" role="button">Go To My Team</a>
                                </div>
                            {% endif %}
                            <div class="col-lg-4">
                                <a style="text-align:center" type="button" class="btn btn-warning btn-lg" href="/teams/all_teams">View All Teams</a>
                            </div>
                            <div class="col-lg-4">
                                <a class="btn btn-info btn-lg" href="#creation_dropdown" data-toggle="tab">Create Team</a>
                            </div>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane fade" id="creation_dropdown">
                                <form action="{% url 'new_team' %}" method="post" class="form">
                                    {% csrf_token %}
                                    {% bootstrap_form team_creation_form  %}
                                    {% buttons %}
                                    <button class="btn btn-success" type="submit" >Create Team</button>
                                    {% endbuttons %}
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
{% else %}
    <body style="margin: auto; width: 50%; padding: 10px; background-image: url('/media/toto.jpg'); background-repeat: no-repeat">
        <h1 style="color:{{message.text_color}}" >{{message.welcome_message}}</h1>
        <div class="col-md-8">
            <div class="panel panel-success">
                <div class="panel-body">
                    <ul class="nav nav-tabs">
                        <div class="col-lg-6">
                            <li>
                                <a class="btn btn-info btn-lg btn-block" href="#login_dropdown" data-toggle="tab">Login</a>
                            </li>
                        </div>
                        <div class="col-lg-6">
                            <li>
                                <a  class="btn btn-info btn-lg btn-block" href="#registration_dropdown" data-toggle="tab">Register</a>
                            </li>
                        </div>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane fade" id="login_dropdown">
                            <form action="{% url 'home' %}" method="post" class="form">
                                {% csrf_token %}
                                {% bootstrap_form login_form %}
                                {% buttons %}
                                <button class="btn btn-success" type="submit" >Login</button>
                                {% endbuttons %}
                            </form>
                        </div>
                        <div class="tab-pane fade" id="registration_dropdown">
                            <form action="{% url 'registration' %}" method="post" class="form" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% bootstrap_form register_form %}
                                {% buttons %}
                                <button type="submit" class="btn btn-info" >Submit</button>
                                {%endbuttons%}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
{% endif %}
{%endblock%}